
name: Pytest
on: [push]
jobs:
  build-model:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Seting up Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Install podules
      - name: Install modules
        run: python3 -m pip install -r requirements.txt

      # Run Build Model
      - name: Run build model
        run: python3 build_model.py

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Seting up Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Install podules
      - name: Install modules
        run: python3 -m pip install -r requirements.txt

      # Run Pytest
      - name: Run test
        run: pytest .